from pathlib import Path

ROOT=Path('profesional')
P=ROOT/'assets/js/modules/service-sheets.js'
AUTH=ROOT/'assets/js/security/auth-permissions.js'
if not P.exists() or not AUTH.exists():
    raise SystemExit('Faltan archivos generados de Hojas de Servicio')

auth=AUTH.read_text(encoding='utf-8')
old="['hojas_servicio','Control de Hojas de Servicio',[['ver','Ver módulo'],['generar','Generar folios'],['asignar_responsable','Asignar a responsable'],['asignar_operador','Asignar a operadores'],['catalogos','Catálogos']]]"
new="['hojas_servicio','Control de Hojas de Servicio',[['ver','Ver módulo'],['generar','Generar folios'],['asignar_responsable','Asignar a responsable'],['asignar_operador','Asignar a operadores'],['comprobar','Comprobar uso / devolución'],['catalogos','Catálogos']]]"
if old in auth:
    auth=auth.replace(old,new,1)
elif "['comprobar','Comprobar uso / devolución']" not in auth:
    raise SystemExit('No se encontró esquema de permisos Hojas de Servicio')
AUTH.write_text(auth,encoding='utf-8')

extra=r'''

/* Tráfico App Profesional · Hojas de Servicio v2 · responsables + comprobación */
(function(){
 if(window.__ccServiceSheetsV2)return;window.__ccServiceSheetsV2=true;
 const sb=()=>window.gmSupabase;
 const esc=v=>String(v==null?'':v).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
 const fmt=v=>v?new Date(v+'T12:00:00').toLocaleDateString('es-MX'):'—';
 const active=xs=>(xs||[]).filter(x=>String(x.estatus||'ACTIVO').toUpperCase()==='ACTIVO');
 const perm=p=>window.CC_ACCESS?.rol==='ADMIN'||(typeof window.ccPerm==='function'&&window.ccPerm('hojas_servicio.'+p));
 let D={};
 async function load(){const r=await sb().rpc('hs_list');if(r.error)throw r.error;if(!r.data?.ok)throw new Error(r.data?.error||'No se pudo cargar');D=r.data;renderAll();return D}
 function modal(title,html,onSave){const ov=document.createElement('div');ov.style='position:fixed;inset:0;background:rgba(15,23,42,.76);z-index:100130;display:flex;align-items:center;justify-content:center;padding:16px';ov.innerHTML='<div style="background:#fff;width:min(820px,97vw);max-height:94vh;overflow:auto;border-radius:16px"><div style="background:#0f172a;color:#fff;padding:15px 18px;display:flex;justify-content:space-between"><strong>'+esc(title)+'</strong><button data-x style="border:0;background:none;color:#fff;font-size:22px">×</button></div><form style="padding:18px">'+html+'<div style="display:flex;justify-content:flex-end;gap:8px;margin-top:15px"><button type="button" class="cc-btn cc-btn-light" data-cancel>Cancelar</button><button type="submit" class="cc-btn cc-btn-primary">Guardar</button></div></form></div>';document.body.appendChild(ov);const close=()=>ov.remove();ov.querySelector('[data-x]').onclick=close;ov.querySelector('[data-cancel]').onclick=close;ov.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('[type=submit]');b.disabled=true;try{await onSave(new FormData(e.currentTarget));close();await load()}catch(err){alert(err.message||err);b.disabled=false}};return ov}
 const opts=(xs,f)=>xs.map(x=>'<option value="'+esc(x.id)+'">'+esc(f(x))+'</option>').join('');
 async function saveCatalog(tipo,item){const r=await sb().rpc('hs_save_catalog',{p_tipo:tipo,p_item:item});if(r.error)throw r.error;if(r.data?.ok===false)throw new Error(r.data.error||'No se pudo guardar')}
 function formResponsable(x={}){if(!perm('catalogos'))return alert('Sin permiso para catálogos.');modal(x.id?'Editar responsable':'Nuevo responsable','<div class="cc-grid"><div class="cc-field"><label>Nombre *</label><input name="nombre" required value="'+esc(x.nombre||'')+'"></div><div class="cc-field"><label>Número empleado</label><input name="numeroEmpleado" value="'+esc(x.numeroEmpleado||'')+'"></div><div class="cc-field"><label>Correo</label><input name="correo" type="email" value="'+esc(x.correo||'')+'"></div><div class="cc-field"><label>Teléfono</label><input name="telefono" value="'+esc(x.telefono||'')+'"></div><div class="cc-field"><label>Estatus</label><select name="estatus"><option '+(x.estatus!=='INACTIVO'?'selected':'')+'>ACTIVO</option><option '+(x.estatus==='INACTIVO'?'selected':'')+'>INACTIVO</option></select></div></div>',fd=>saveCatalog('RESPONSABLE',{id:x.id||'',nombre:fd.get('nombre'),numeroEmpleado:fd.get('numeroEmpleado'),correo:fd.get('correo'),telefono:fd.get('telefono'),estatus:fd.get('estatus')}))}
 function assignResponsible(){if(!perm('asignar_responsable'))return alert('Sin permiso.');const rs=active(D.responsables),ss=active(D.series),ys=active(D.anios);if(!rs.length)return alert('Primero agrega un responsable en Catálogos.');modal('Asignar rango a responsable','<div class="cc-config-alert" style="margin-bottom:12px">El responsable debe provenir del catálogo interno de Hojas de Servicio. Al guardar se generará el enlace de aceptación y firma.</div><div class="cc-grid"><div class="cc-field"><label>Serie *</label><select name="serieId" required>'+opts(ss,x=>x.codigo)+'</select></div><div class="cc-field"><label>Año *</label><select name="anioId" required>'+opts(ys,x=>x.anio)+'</select></div><div class="cc-field"><label>Desde *</label><input name="desde" type="number" min="0" max="999999" required></div><div class="cc-field"><label>Hasta *</label><input name="hasta" type="number" min="0" max="999999" required></div><div class="cc-field"><label>Responsable *</label><select name="responsableId" required>'+opts(rs,x=>x.nombre+(x.numeroEmpleado?' · '+x.numeroEmpleado:''))+'</select></div></div>',async fd=>{const r=await sb().rpc('hs_create_responsible_assignment',{p_item:{serieId:fd.get('serieId'),anioId:fd.get('anioId'),desde:Number(fd.get('desde')),hasta:Number(fd.get('hasta')),responsableId:fd.get('responsableId'),hours:168}});if(r.error)throw r.error;if(r.data?.ok===false)throw new Error(r.data.error||'No se pudo asignar');const url=location.origin+location.pathname.replace(/[^/]+$/,'')+'hojas-servicio-aceptar.html?t='+encodeURIComponent(r.data.token);try{await navigator.clipboard.writeText(url)}catch(_){ }prompt('Asignación creada. Comparte este enlace para aceptación y firma:',url)})}
 function comprobacionModal(folio){if(!perm('comprobar'))return alert('Sin permiso para comprobar hojas.');const today=new Date().toISOString().slice(0,10);const ov=modal('Comprobar '+folio.folio,'<div class="cc-config-alert"><strong>Operador:</strong> '+esc(folio.operador||'—')+'<br><strong>Responsable:</strong> '+esc(folio.responsable||'—')+'</div><div class="cc-field" style="margin-top:12px"><label>Movimiento *</label><select name="tipo"><option value="USO">Hoja utilizada</option><option value="DEVOLUCION_BLANCO">Regresó hoja en blanco</option></select></div><div class="cc-grid"><div class="cc-field"><label>Fecha *</label><input name="fecha" type="date" value="'+today+'" required></div><div class="cc-field" data-service><label>Tipo / servicio realizado *</label><input name="servicio" placeholder="Campo libre"></div></div><div class="cc-field"><label>Observaciones</label><textarea name="observaciones"></textarea></div>',async fd=>{const tipo=fd.get('tipo');const rpc=tipo==='USO'?'hs_mark_used':'hs_return_blank';if(tipo==='USO'&&!String(fd.get('servicio')||'').trim())throw new Error('Indica el servicio realizado.');const r=await sb().rpc(rpc,{p_item:{folioId:folio.id,fecha:fd.get('fecha'),servicio:fd.get('servicio'),observaciones:fd.get('observaciones')}});if(r.error)throw r.error;if(r.data?.ok===false)throw new Error(r.data.error||'No se pudo guardar')});const type=ov.querySelector('[name=tipo]'),service=ov.querySelector('[data-service]'),inp=ov.querySelector('[name=servicio]');const sync=()=>{const used=type.value==='USO';service.style.display=used?'':'none';inp.required=used};type.onchange=sync;sync()}
 function ensureUi(){const panel=document.getElementById('ccPanelHojasServicio');if(!panel)return;const nav=[...panel.querySelectorAll('[data-hsv]')];if(nav.length&&!panel.querySelector('[data-hsv="Comprobacion"]')){const b=document.createElement('button');b.className='cc-btn cc-btn-light';b.dataset.hsv='Comprobacion';b.innerHTML='<i class="fa-solid fa-clipboard-check mr-1"></i>Comprobación';const cat=panel.querySelector('[data-hsv="Catalogos"]');cat?cat.before(b):nav[0].parentNode.appendChild(b);b.onclick=()=>openComprobacion(b)}let view=document.getElementById('hsViewComprobacion');if(!view){view=document.createElement('div');view.id='hsViewComprobacion';view.className='hs-view';view.style.display='none';view.innerHTML='<div class="cc-toolbar"><div><strong>Comprobación de hojas</strong><div class="cc-note">Marca hojas utilizadas o devuelve hojas en blanco al responsable.</div></div><button class="cc-btn cc-btn-light" data-hsc-refresh>Actualizar</button></div><div class="cc-inv-wrap"><table class="cc-ant-table"><thead><tr><th>FOLIO</th><th>OPERADOR</th><th>RESPONSABLE</th><th>ASIGNADO</th><th>ACCIÓN</th></tr></thead><tbody id="hsCompPendBody"></tbody></table></div><div class="cc-config-card" style="margin-top:14px"><strong>Historial de comprobaciones</strong><div class="cc-inv-wrap" style="margin-top:8px"><table class="cc-ant-table"><thead><tr><th>FOLIO</th><th>MOVIMIENTO</th><th>FECHA</th><th>SERVICIO</th><th>OPERADOR</th><th>RESPONSABLE</th></tr></thead><tbody id="hsCompHistBody"></tbody></table></div></div>';panel.appendChild(view);view.querySelector('[data-hsc-refresh]').onclick=()=>load().catch(e=>alert(e.message||e))}const catView=document.getElementById('hsViewCatalogos');if(catView&&!document.getElementById('hsRespCatalogCard')){const card=document.createElement('div');card.id='hsRespCatalogCard';card.className='cc-config-card';card.style.marginTop='12px';card.innerHTML='<div class="cc-toolbar"><strong>Responsables</strong><button class="cc-btn cc-btn-primary" data-hsr-add>Agregar responsable</button></div><div id="hsRespCatalogList"></div>';catView.appendChild(card);card.querySelector('[data-hsr-add]').onclick=()=>formResponsable()}}
 function openComprobacion(btn){const panel=document.getElementById('ccPanelHojasServicio');panel.querySelectorAll('.hs-view').forEach(x=>x.style.display='none');document.getElementById('hsViewComprobacion').style.display='block';panel.querySelectorAll('[data-hsv]').forEach(x=>x.className='cc-btn cc-btn-light');btn.className='cc-btn cc-btn-primary';load().catch(e=>alert(e.message||e))}
 function renderAll(){ensureUi();const rr=document.getElementById('hsRespCatalogList');if(rr)rr.innerHTML=(D.responsables||[]).map(x=>'<div style="padding:8px;border-bottom:1px solid #e2e8f0;display:flex;justify-content:space-between;gap:8px"><span><strong>'+esc(x.nombre)+'</strong><small style="display:block;color:#64748b">'+esc(x.numeroEmpleado||'')+(x.correo?' · '+esc(x.correo):'')+' · '+esc(x.estatus||'')+'</small></span><button class="cc-btn cc-btn-light" data-hsr="'+esc(x.id)+'">Editar</button></div>').join('')||'<div class="cc-note">Sin responsables registrados.</div>';rr?.querySelectorAll('[data-hsr]').forEach(b=>b.onclick=()=>formResponsable((D.responsables||[]).find(x=>x.id===b.dataset.hsr)||{}));const pb=document.getElementById('hsCompPendBody');if(pb)pb.innerHTML=(D.foliosAsignadosOperador||[]).map(x=>'<tr><td><strong>'+esc(x.folio)+'</strong></td><td>'+esc(x.operador||'—')+'</td><td>'+esc(x.responsable||'—')+'</td><td>'+esc(x.asignadoAt?new Date(x.asignadoAt).toLocaleString('es-MX'):'—')+'</td><td><button class="cc-btn cc-btn-primary" data-hsc="'+esc(x.id)+'">Comprobar</button></td></tr>').join('')||'<tr><td colspan="5" style="text-align:center;padding:20px">No hay hojas pendientes con operadores.</td></tr>';pb?.querySelectorAll('[data-hsc]').forEach(b=>b.onclick=()=>comprobacionModal((D.foliosAsignadosOperador||[]).find(x=>x.id===b.dataset.hsc)||{}));const hb=document.getElementById('hsCompHistBody');if(hb)hb.innerHTML=(D.comprobaciones||[]).map(x=>'<tr><td><strong>'+esc(x.folio)+'</strong></td><td>'+esc(x.tipo==='USO'?'UTILIZADA':'DEVUELTA EN BLANCO')+'</td><td>'+fmt(x.fecha)+'</td><td>'+esc(x.servicio||'—')+'</td><td>'+esc(x.operador||'—')+'</td><td>'+esc(x.responsable||'—')+'</td></tr>').join('')||'<tr><td colspan="6" style="text-align:center;padding:20px">Sin comprobaciones registradas.</td></tr>';const k=document.getElementById('hsKpis');if(k&&!k.querySelector('[data-hs-utilizados]')){const d=document.createElement('div');d.className='cc-ant-kpi';d.dataset.hsUtilizados='1';d.innerHTML='<small>Utilizados</small><strong>'+Number(D.resumen?.utilizados||0).toLocaleString('es-MX')+'</strong>';k.appendChild(d)}else if(k){const s=k.querySelector('[data-hs-utilizados] strong');if(s)s.textContent=Number(D.resumen?.utilizados||0).toLocaleString('es-MX')}}
 function install(){ensureUi();const panel=document.getElementById('ccPanelHojasServicio');if(!panel)return;const oldResp=panel.querySelector('[data-resp]');if(oldResp)oldResp.onclick=()=>assignResponsible();load().catch(e=>console.warn('Hojas servicio v2',e));setTimeout(()=>{const b=panel.querySelector('[data-resp]');if(b)b.onclick=()=>assignResponsible()},500)}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,1300));else setTimeout(install,1300);
})();
'''

text=P.read_text(encoding='utf-8')
marker='/* Tráfico App Profesional · Hojas de Servicio v2 · responsables + comprobación */'
if marker not in text:
    text += extra
P.write_text(text,encoding='utf-8')
print('Hojas de Servicio v2: catálogo responsables, comprobación y devolución en blanco integrados')
