from pathlib import Path

P=Path('profesional/assets/js/modules/configuracion.js')
if not P.exists(): raise SystemExit('No existe configuracion.js')
s=P.read_text(encoding='utf-8')
marker='/* Tráfico App Profesional · Catálogos generales de personas v2 */'
if marker in s:
    print('catálogos generales v2 ya aplicados'); raise SystemExit(0)
# Si una compilación conserva la versión anterior, retirarla antes de insertar v2.
old='/* Tráfico App Profesional · Catálogos generales de personas v1 */'
if old in s:
    s=s[:s.index(old)].rstrip()+"\n"
js=r'''

/* Tráfico App Profesional · Catálogos generales de personas v2 */
(function(){
 if(window.__ccGeneralPeopleCatalogsV2)return;window.__ccGeneralPeopleCatalogsV2=true;
 const sb=()=>window.gmSupabase;
 const esc=v=>String(v==null?'':v).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
 let D={operadores:[],beneficiarios:[],responsablesHojas:[]};
 const canEdit=()=>window.CC_ACCESS?.rol==='ADMIN'||(typeof window.ccPerm==='function'&&window.ccPerm('configuracion.editar'));
 async function load(){const r=await sb().rpc('cc_general_catalogs');if(r.error)throw r.error;D=r.data||D;render();return D;}
 function modal(title,html,onSave){const ov=document.createElement('div');ov.style='position:fixed;inset:0;background:rgba(15,23,42,.76);z-index:100400;display:flex;align-items:center;justify-content:center;padding:16px';ov.innerHTML='<div style="background:#fff;width:min(760px,97vw);max-height:94vh;overflow:auto;border-radius:16px"><div style="background:#0f172a;color:#fff;padding:15px 18px;display:flex;justify-content:space-between"><strong>'+esc(title)+'</strong><button data-x style="border:0;background:none;color:#fff;font-size:22px">×</button></div><form style="padding:18px">'+html+'<div style="display:flex;justify-content:flex-end;gap:8px;margin-top:15px"><button type="button" class="cc-btn cc-btn-light" data-cancel>Cancelar</button><button type="submit" class="cc-btn cc-btn-primary">Guardar</button></div></form></div>';document.body.appendChild(ov);const close=()=>ov.remove();ov.querySelector('[data-x]').onclick=close;ov.querySelector('[data-cancel]').onclick=close;ov.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('[type=submit]');b.disabled=true;try{await onSave(new FormData(e.currentTarget));close();await load();window.ccAntLoad?.(true);}catch(err){alert(err.message||err);b.disabled=false}};}
 async function save(tipo,x,fd){const r=await sb().rpc('cc_general_save_catalog',{p_tipo:tipo,p_item:{id:x.id||'',nombre:fd.get('nombre'),numeroEmpleado:fd.get('numeroEmpleado'),correo:fd.get('correo'),telefono:fd.get('telefono'),estatus:fd.get('estatus')}});if(r.error)throw r.error;}
 function form(tipo,x={}){if(!canEdit())return alert('Sin permiso para modificar Configuración.');const labels={OPERADOR:'Operador',BENEFICIARIO:'Beneficiario',RESPONSABLE_HOJAS:'Responsable de Hojas'};const hasMail=tipo==='RESPONSABLE_HOJAS';modal((x.id?'Editar ':'Nuevo ')+labels[tipo],'<div class="cc-grid"><div class="cc-field"><label>Nombre *</label><input name="nombre" required value="'+esc(x.nombre||'')+'"></div><div class="cc-field"><label>Número empleado</label><input name="numeroEmpleado" value="'+esc(x.numeroEmpleado||'')+'"></div>'+(hasMail?'<div class="cc-field"><label>Correo</label><input type="email" name="correo" value="'+esc(x.correo||'')+'"></div>':'')+'<div class="cc-field"><label>Teléfono</label><input name="telefono" value="'+esc(x.telefono||'')+'"></div><div class="cc-field"><label>Estatus</label><select name="estatus"><option '+(x.estatus!=='INACTIVO'?'selected':'')+'>ACTIVO</option><option '+(x.estatus==='INACTIVO'?'selected':'')+'>INACTIVO</option></select></div></div>',fd=>save(tipo,x,fd));}
 function configPanel(){return document.getElementById('ccPanelConfiguracion')||document.querySelector('#controlCajasSection .cc-panel.active')||[...document.querySelectorAll('#controlCajasSection .cc-panel')].find(x=>/configuraci/i.test(x.id||''));}
 const cards=[['OPERADOR','Operadores','Usados por Anticipos y Hojas de Servicio.'],['BENEFICIARIO','Beneficiarios','Usados por Anticipos.'],['RESPONSABLE_HOJAS','Responsables de Hojas','Usados por Control de Hojas de Servicio.']];
 function ensure(){const p=configPanel();if(!p)return null;document.getElementById('ccGeneralPeopleCatalogs')?.remove();let host=document.getElementById('ccGeneralPeopleCatalogsV2');if(!host){host=document.createElement('div');host.id='ccGeneralPeopleCatalogsV2';host.style='display:contents';cards.forEach(([tipo,titulo,nota])=>{const card=document.createElement('div');card.className='cc-config-card';card.dataset.gpcCard=tipo;card.innerHTML='<div class="cc-toolbar"><div><strong>'+titulo+'</strong><div class="cc-note">'+nota+'</div></div><div style="display:flex;gap:6px"><button class="cc-btn cc-btn-light" data-gpc-refresh title="Actualizar">↻</button><button class="cc-btn cc-btn-primary" data-gpc-add="'+tipo+'">Agregar</button></div></div><div data-gpc-list="'+tipo+'"></div>';p.appendChild(card);});p.appendChild(host);p.querySelectorAll('[data-gpc-refresh]').forEach(b=>b.onclick=()=>load().catch(e=>alert(e.message||e)));p.querySelectorAll('[data-gpc-add]').forEach(b=>b.onclick=()=>form(b.dataset.gpcAdd));}return p;}
 function listHtml(xs,tipo){return (xs||[]).map(x=>'<div style="padding:8px;border-bottom:1px solid #e2e8f0;display:flex;justify-content:space-between;gap:8px"><span><strong>'+esc(x.nombre)+'</strong><small style="display:block;color:#64748b">'+esc(x.numeroEmpleado||'')+(x.correo?' · '+esc(x.correo):'')+(x.telefono?' · '+esc(x.telefono):'')+' · '+esc(x.estatus||'')+'</small></span><button class="cc-btn cc-btn-light" data-edit="'+esc(tipo)+'|'+esc(x.id)+'">Editar</button></div>').join('')||'<div class="cc-note">Sin registros.</div>';}
 function hideDuplicates(){document.getElementById('hsRespCatalogCard')?.remove();document.getElementById('hsOpCatalogCard')?.remove();const av=document.getElementById('ccAntViewCatalogos');if(av){av.querySelectorAll('.cc-config-card').forEach(c=>{const t=(c.querySelector('strong')?.textContent||'').trim();if(t==='Operadores'||t==='Responsables'||t==='Beneficiarios')c.remove();});}}
 function render(){const p=ensure();if(!p)return;[['OPERADOR',D.operadores],['BENEFICIARIO',D.beneficiarios],['RESPONSABLE_HOJAS',D.responsablesHojas]].forEach(([tipo,xs])=>{const el=p.querySelector('[data-gpc-list="'+tipo+'"]');if(el)el.innerHTML=listHtml(xs,tipo);});p.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const [tipo,id]=b.dataset.edit.split('|');const src=tipo==='OPERADOR'?D.operadores:tipo==='BENEFICIARIO'?D.beneficiarios:D.responsablesHojas;form(tipo,(src||[]).find(x=>x.id===id)||{});});hideDuplicates();}
 function wire(){const old=window.ccTab;if(typeof old==='function'&&!old.__generalPeopleV2){const w=function(tab,btn){const r=old.apply(this,arguments);if(tab==='configuracion')setTimeout(()=>load().catch(e=>console.warn('Catálogos generales',e)),80);setTimeout(hideDuplicates,80);return r};w.__generalPeopleV2=true;window.ccTab=w;}const rc=window.ccRenderConfiguracion;if(typeof rc==='function'&&!rc.__generalPeopleV2){const w=function(){const r=rc.apply(this,arguments);setTimeout(()=>load().catch(()=>{}),80);return r};w.__generalPeopleV2=true;window.ccRenderConfiguracion=w;}}
 async function boot(){if(!window.CC_AUTH_READY||!window.gmSupabase)return setTimeout(boot,500);wire();hideDuplicates();try{await load()}catch(e){console.warn('Catálogos generales',e)}new MutationObserver(()=>hideDuplicates()).observe(document.getElementById('controlCajasSection')||document.body,{childList:true,subtree:true});}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,1900));else setTimeout(boot,1900);
})();
'''
s += js
P.write_text(s,encoding='utf-8')
print('Operadores, Beneficiarios y Responsables de Hojas integrados como tarjetas directas de Configuración')
