from pathlib import Path

P=Path('profesional/assets/js/modules/service-sheets.js')
if not P.exists(): raise SystemExit('No existe service-sheets.js')
s=P.read_text(encoding='utf-8')
marker='/* Tráfico App Profesional · Hojas de Servicio v6 · catálogos propios responsables + operadores */'
if marker in s:
    print('v6 ya aplicado'); raise SystemExit(0)
js=r'''

/* Tráfico App Profesional · Hojas de Servicio v6 · catálogos propios responsables + operadores */
(function(){
 if(window.__ccServiceSheetsV6)return;window.__ccServiceSheetsV6=true;
 const sb=()=>window.gmSupabase;
 const esc=v=>String(v==null?'':v).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
 const six=v=>String(Math.max(0,Number(v)||0)).padStart(6,'0');
 let D={};
 const active=xs=>(xs||[]).filter(x=>String(x.estatus||'ACTIVO').toUpperCase()==='ACTIVO');
 const opts=(xs,f)=>xs.map(x=>'<option value="'+esc(x.id)+'">'+esc(f(x))+'</option>').join('');
 async function load(){const r=await sb().rpc('hs_list');if(r.error)throw r.error;D=r.data||{};renderCatalogs();wireActions();return D}
 function modal(title,html,onSave){const ov=document.createElement('div');ov.style='position:fixed;inset:0;background:rgba(15,23,42,.76);z-index:100260;display:flex;align-items:center;justify-content:center;padding:16px';ov.innerHTML='<div style="background:#fff;width:min(820px,97vw);max-height:94vh;overflow:auto;border-radius:16px"><div style="background:#0f172a;color:#fff;padding:15px 18px;display:flex;justify-content:space-between"><strong>'+esc(title)+'</strong><button data-x style="border:0;background:none;color:#fff;font-size:22px">×</button></div><form style="padding:18px">'+html+'<div style="display:flex;justify-content:flex-end;gap:8px;margin-top:15px"><button type="button" class="cc-btn cc-btn-light" data-cancel>Cancelar</button><button type="submit" class="cc-btn cc-btn-primary">Guardar</button></div></form></div>';document.body.appendChild(ov);const close=()=>ov.remove();ov.querySelector('[data-x]').onclick=close;ov.querySelector('[data-cancel]').onclick=close;ov.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('[type=submit]');b.disabled=true;try{await onSave(new FormData(e.currentTarget));close();await load()}catch(err){alert(err.message||err);b.disabled=false}};return ov}
 async function saveCatalog(tipo,item){const r=await sb().rpc('hs_save_catalog',{p_tipo:tipo,p_item:item});if(r.error)throw r.error}
 function personForm(tipo,x={}){const isOp=tipo==='OPERADOR',label=isOp?'operador':'responsable';modal((x.id?'Editar ':'Nuevo ')+label,'<div class="cc-grid"><div class="cc-field"><label>Nombre *</label><input name="nombre" required value="'+esc(x.nombre||'')+'"></div><div class="cc-field"><label>Número empleado</label><input name="numeroEmpleado" value="'+esc(x.numeroEmpleado||'')+'"></div><div class="cc-field"><label>Correo</label><input name="correo" type="email" value="'+esc(x.correo||'')+'"></div><div class="cc-field"><label>Teléfono</label><input name="telefono" value="'+esc(x.telefono||'')+'"></div><div class="cc-field"><label>Estatus</label><select name="estatus"><option '+(x.estatus!=='INACTIVO'?'selected':'')+'>ACTIVO</option><option '+(x.estatus==='INACTIVO'?'selected':'')+'>INACTIVO</option></select></div></div>',fd=>saveCatalog(tipo,{id:x.id||'',nombre:fd.get('nombre'),numeroEmpleado:fd.get('numeroEmpleado'),correo:fd.get('correo'),telefono:fd.get('telefono'),estatus:fd.get('estatus')}))}
 function assignResponsible(){const rs=active(D.responsables),ss=active(D.series),ys=active(D.anios);if(!rs.length)return alert('Primero agrega un responsable en Configuración > Catálogos de Hojas de Servicio.');modal('Asignar rango a responsable','<div class="cc-config-alert" style="margin-bottom:12px">El responsable se selecciona exclusivamente del catálogo de Responsables de Hojas de Servicio.</div><div class="cc-grid"><div class="cc-field"><label>Serie *</label><select name="serieId" required>'+opts(ss,x=>x.codigo)+'</select></div><div class="cc-field"><label>Año *</label><select name="anioId" required>'+opts(ys,x=>x.anio)+'</select></div><div class="cc-field"><label>Desde *</label><input name="desde" type="number" min="0" max="999999" required></div><div class="cc-field"><label>Hasta *</label><input name="hasta" type="number" min="0" max="999999" required></div><div class="cc-field"><label>Responsable *</label><select name="responsableId" required>'+opts(rs,x=>x.nombre+(x.numeroEmpleado?' · '+x.numeroEmpleado:''))+'</select></div></div>',async fd=>{const r=await sb().rpc('hs_create_responsible_assignment',{p_item:{serieId:fd.get('serieId'),anioId:fd.get('anioId'),desde:Number(fd.get('desde')),hasta:Number(fd.get('hasta')),responsableId:fd.get('responsableId'),hours:168}});if(r.error)throw r.error;const url=location.origin+location.pathname.replace(/[^/]+$/,'')+'hojas-servicio-aceptar.html?t='+encodeURIComponent(r.data.token);try{await navigator.clipboard.writeText(url)}catch(_){ }prompt('Asignación creada. Comparte este enlace para aceptación y firma:',url)})}
 function assignOperator(){const aa=(D.asignacionesResponsable||[]).filter(x=>x.estatus==='ACEPTADA'),ops=active(D.operadores);if(!aa.length)return alert('No hay rangos aceptados por responsables.');if(!ops.length)return alert('Primero agrega operadores en Configuración > Catálogos de Hojas de Servicio.');modal('Repartir folios a operador','<div class="cc-config-alert" style="margin-bottom:12px">El operador se selecciona exclusivamente del catálogo de Operadores de Hojas de Servicio.</div><div class="cc-grid"><div class="cc-field"><label>Custodia del responsable *</label><select name="asignacionId" required>'+opts(aa,x=>x.responsableNombre+' · '+x.serie+'-'+x.anio+' · '+six(x.desde)+' a '+six(x.hasta))+'</select></div><div class="cc-field"><label>Operador *</label><select name="operadorId" required>'+opts(ops,x=>x.nombre+(x.numeroEmpleado?' · '+x.numeroEmpleado:''))+'</select></div><div class="cc-field"><label>Desde *</label><input name="desde" type="number" min="0" max="999999" required></div><div class="cc-field"><label>Hasta *</label><input name="hasta" type="number" min="0" max="999999" required></div></div><div class="cc-field"><label>Observaciones</label><textarea name="observaciones"></textarea></div>',async fd=>{const r=await sb().rpc('hs_assign_operator_range',{p_item:{asignacionId:fd.get('asignacionId'),operadorId:fd.get('operadorId'),desde:Number(fd.get('desde')),hasta:Number(fd.get('hasta')),observaciones:fd.get('observaciones')}});if(r.error)throw r.error;alert('Folios asignados al operador: '+Number(r.data?.asignados||0))})}
 function ensureCards(){const view=document.getElementById('hsViewCatalogos');if(!view)return;let r=document.getElementById('hsRespCatalogCard');if(!r){r=document.createElement('div');r.id='hsRespCatalogCard';r.className='cc-config-card';r.style.marginTop='12px';r.innerHTML='<div class="cc-toolbar"><strong>Responsables</strong><button class="cc-btn cc-btn-primary" data-add-resp>Agregar responsable</button></div><div id="hsRespCatalogList"></div>';view.appendChild(r)}let o=document.getElementById('hsOpCatalogCard');if(!o){o=document.createElement('div');o.id='hsOpCatalogCard';o.className='cc-config-card';o.style.marginTop='12px';o.innerHTML='<div class="cc-toolbar"><div><strong>Operadores</strong><div class="cc-note">Catálogo exclusivo para repartir Hojas de Servicio.</div></div><button class="cc-btn cc-btn-primary" data-add-op>Agregar operador</button></div><div id="hsOpCatalogList"></div>';view.appendChild(o)}r.querySelector('[data-add-resp]')?.addEventListener('click',()=>personForm('RESPONSABLE'));o.querySelector('[data-add-op]')?.addEventListener('click',()=>personForm('OPERADOR'))}
 function renderCatalogs(){ensureCards();const rr=document.getElementById('hsRespCatalogList'),oo=document.getElementById('hsOpCatalogList');if(rr){rr.innerHTML=(D.responsables||[]).map(x=>'<div style="padding:8px;border-bottom:1px solid #e2e8f0;display:flex;justify-content:space-between;gap:8px"><span><strong>'+esc(x.nombre)+'</strong><small style="display:block;color:#64748b">'+esc(x.numeroEmpleado||'')+(x.correo?' · '+esc(x.correo):'')+' · '+esc(x.estatus||'')+'</small></span><button class="cc-btn cc-btn-light" data-edit-resp="'+esc(x.id)+'">Editar</button></div>').join('')||'<div class="cc-note">Sin responsables registrados.</div>';rr.querySelectorAll('[data-edit-resp]').forEach(b=>b.onclick=()=>personForm('RESPONSABLE',(D.responsables||[]).find(x=>x.id===b.dataset.editResp)||{}))}if(oo){oo.innerHTML=(D.operadores||[]).map(x=>'<div style="padding:8px;border-bottom:1px solid #e2e8f0;display:flex;justify-content:space-between;gap:8px"><span><strong>'+esc(x.nombre)+'</strong><small style="display:block;color:#64748b">'+esc(x.numeroEmpleado||'')+(x.correo?' · '+esc(x.correo):'')+' · '+esc(x.estatus||'')+'</small></span><button class="cc-btn cc-btn-light" data-edit-op="'+esc(x.id)+'">Editar</button></div>').join('')||'<div class="cc-note">Sin operadores registrados.</div>';oo.querySelectorAll('[data-edit-op]').forEach(b=>b.onclick=()=>personForm('OPERADOR',(D.operadores||[]).find(x=>x.id===b.dataset.editOp)||{}))}}
 function wireActions(){const panel=document.getElementById('ccPanelHojasServicio');if(!panel)return;const br=panel.querySelector('[data-resp]'),bo=panel.querySelector('[data-op]');if(br)br.onclick=assignResponsible;if(bo)bo.onclick=assignOperator}
 async function boot(){if(!window.gmSupabase)return setTimeout(boot,500);try{await load()}catch(e){console.warn('HS v6',e)}setInterval(()=>{const p=document.getElementById('ccPanelHojasServicio');if(p&&p.classList.contains('active'))load().catch(()=>{})},30000)}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,1800));else setTimeout(boot,1800);
})();
'''
s+=js
P.write_text(s,encoding='utf-8')
print('Hojas de Servicio v6 agregado')
