from pathlib import Path

P=Path('profesional/assets/js/modules/configuracion.js')
if not P.exists(): raise SystemExit('No existe configuracion.js')
s=P.read_text(encoding='utf-8')
for old in ['/* Tráfico App Profesional · Catálogos generales de personas v1 */','/* Tráfico App Profesional · Catálogos generales de personas v2 */']:
    if old in s:
        s=s[:s.index(old)].rstrip()+"\n"
marker='/* Tráfico App Profesional · Catálogos generales de personas v3 · menú Configuración */'
js=r'''

/* Tráfico App Profesional · Catálogos generales de personas v3 · menú Configuración */
(function(){
 if(window.__ccGeneralPeopleCatalogsV3)return; window.__ccGeneralPeopleCatalogsV3=true;
 const sb=()=>window.gmSupabase;
 const esc=v=>String(v==null?'':v).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
 let D={operadores:[],beneficiarios:[],responsablesHojas:[]};
 const defs={operadores:['OPERADOR','Operadores'],beneficiarios:['BENEFICIARIO','Beneficiarios'],responsablesHojas:['RESPONSABLE_HOJAS','Responsables de Hojas']};
 const canEdit=()=>window.CC_ACCESS?.rol==='ADMIN'||(typeof window.ccPerm==='function'&&window.ccPerm('configuracion.editar'));
 async function load(){const r=await sb().rpc('cc_general_catalogs');if(r.error)throw r.error;D=r.data||D;render();return D;}
 function modal(title,html,onSave){const ov=document.createElement('div');ov.style='position:fixed;inset:0;background:rgba(15,23,42,.76);z-index:100400;display:flex;align-items:center;justify-content:center;padding:16px';ov.innerHTML='<div style="background:#fff;width:min(760px,97vw);max-height:94vh;overflow:auto;border-radius:16px"><div style="background:#0f172a;color:#fff;padding:15px 18px;display:flex;justify-content:space-between"><strong>'+esc(title)+'</strong><button data-x style="border:0;background:none;color:#fff;font-size:22px">×</button></div><form style="padding:18px">'+html+'<div style="display:flex;justify-content:flex-end;gap:8px;margin-top:15px"><button type="button" class="cc-btn cc-btn-light" data-cancel>Cancelar</button><button type="submit" class="cc-btn cc-btn-primary">Guardar</button></div></form></div>';document.body.appendChild(ov);const close=()=>ov.remove();ov.querySelector('[data-x]').onclick=close;ov.querySelector('[data-cancel]').onclick=close;ov.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('[type=submit]');b.disabled=true;try{await onSave(new FormData(e.currentTarget));close();await load();window.ccAntLoad?.(true)}catch(err){alert(err.message||err);b.disabled=false}};}
 async function save(tipo,x,fd){const r=await sb().rpc('cc_general_save_catalog',{p_tipo:tipo,p_item:{id:x.id||'',nombre:fd.get('nombre'),numeroEmpleado:fd.get('numeroEmpleado'),correo:fd.get('correo'),telefono:fd.get('telefono'),estatus:fd.get('estatus')}});if(r.error)throw r.error;}
 function form(tipo,x={}){if(!canEdit())return alert('Sin permiso para modificar Configuración.');const labels={OPERADOR:'Operador',BENEFICIARIO:'Beneficiario',RESPONSABLE_HOJAS:'Responsable de Hojas'};const mail=tipo==='RESPONSABLE_HOJAS';modal((x.id?'Editar ':'Nuevo ')+labels[tipo],'<div class="cc-grid"><div class="cc-field"><label>Nombre *</label><input name="nombre" required value="'+esc(x.nombre||'')+'"></div><div class="cc-field"><label>Número empleado</label><input name="numeroEmpleado" value="'+esc(x.numeroEmpleado||'')+'"></div>'+(mail?'<div class="cc-field"><label>Correo</label><input type="email" name="correo" value="'+esc(x.correo||'')+'"></div>':'')+'<div class="cc-field"><label>Teléfono</label><input name="telefono" value="'+esc(x.telefono||'')+'"></div><div class="cc-field"><label>Estatus</label><select name="estatus"><option '+(x.estatus!=='INACTIVO'?'selected':'')+'>ACTIVO</option><option '+(x.estatus==='INACTIVO'?'selected':'')+'>INACTIVO</option></select></div></div>',fd=>save(tipo,x,fd));}
 function panel(){return document.getElementById('ccPanelConfiguracion');}
 function nav(){const p=panel();return p?.querySelector('.cc-config-nav')||p?.querySelector('.cc-config-sidebar')||p?.querySelector('.cc-config-menu')||p?.querySelector('.cc-config-nav-btn')?.parentElement;}
 function ensure(){const p=panel(),n=nav();if(!p||!n)return false;document.getElementById('ccGeneralPeopleCatalogs')?.remove();document.getElementById('ccGeneralPeopleCatalogsV2')?.remove();Object.entries(defs).forEach(([key,[tipo,titulo]])=>{let b=n.querySelector('[data-gpc-nav="'+key+'"]');if(!b){b=document.createElement('button');b.type='button';b.className='cc-config-nav-btn';b.dataset.gpcNav=key;b.textContent=titulo;b.onclick=function(){window.ccConfigSection?.(key,b);setTimeout(()=>load().catch(e=>console.warn('Catálogo general',e)),20)};n.appendChild(b)}let sec=document.getElementById('ccConfig'+key.charAt(0).toUpperCase()+key.slice(1));if(!sec){sec=document.createElement('div');sec.id='ccConfig'+key.charAt(0).toUpperCase()+key.slice(1);sec.className='cc-config-section';sec.innerHTML='<div class="cc-config-card"><div class="cc-toolbar"><div><strong>'+titulo+'</strong><div class="cc-note">Catálogo general de Tráfico App.</div></div><div style="display:flex;gap:6px"><button class="cc-btn cc-btn-light" data-gpc-refresh>Actualizar</button><button class="cc-btn cc-btn-primary" data-gpc-add="'+tipo+'">Agregar</button></div></div><div data-gpc-list="'+tipo+'" style="margin-top:10px"></div></div>';p.appendChild(sec);sec.querySelector('[data-gpc-refresh]').onclick=()=>load().catch(e=>alert(e.message||e));sec.querySelector('[data-gpc-add]').onclick=()=>form(tipo)}});return true;}
 function listHtml(xs,tipo){return (xs||[]).map(x=>'<div style="padding:9px 4px;border-bottom:1px solid #e2e8f0;display:flex;align-items:center;justify-content:space-between;gap:10px"><span><strong>'+esc(x.nombre)+'</strong><small style="display:block;color:#64748b">'+esc(x.numeroEmpleado||'')+(x.correo?' · '+esc(x.correo):'')+(x.telefono?' · '+esc(x.telefono):'')+' · '+esc(x.estatus||'')+'</small></span><button class="cc-btn cc-btn-light" data-gpc-edit="'+tipo+'|'+esc(x.id)+'">Editar</button></div>').join('')||'<div class="cc-note">Sin registros.</div>';}
 function hideDuplicates(){document.getElementById('hsRespCatalogCard')?.remove();document.getElementById('hsOpCatalogCard')?.remove();const av=document.getElementById('ccAntViewCatalogos');if(av)av.querySelectorAll('.cc-config-card').forEach(c=>{const t=(c.querySelector('strong')?.textContent||'').trim();if(['Operadores','Responsables','Beneficiarios'].includes(t))c.remove()})}
 function render(){if(!ensure())return;[['OPERADOR',D.operadores],['BENEFICIARIO',D.beneficiarios],['RESPONSABLE_HOJAS',D.responsablesHojas]].forEach(([tipo,xs])=>{const el=panel().querySelector('[data-gpc-list="'+tipo+'"]');if(el)el.innerHTML=listHtml(xs,tipo)});panel().querySelectorAll('[data-gpc-edit]').forEach(b=>b.onclick=()=>{const [tipo,id]=b.dataset.gpcEdit.split('|');const src=tipo==='OPERADOR'?D.operadores:tipo==='BENEFICIARIO'?D.beneficiarios:D.responsablesHojas;form(tipo,(src||[]).find(x=>x.id===id)||{})});hideDuplicates();}
 function wire(){const old=window.ccRenderConfiguracion;if(typeof old==='function'&&!old.__gpcV3){const w=function(){const r=old.apply(this,arguments);setTimeout(()=>{ensure();render()},20);return r};w.__gpcV3=true;window.ccRenderConfiguracion=w}}
 async function boot(){if(!window.CC_AUTH_READY||!window.gmSupabase)return setTimeout(boot,400);wire();ensure();hideDuplicates();try{await load()}catch(e){console.warn('Catálogos generales',e)}new MutationObserver(()=>{ensure();hideDuplicates()}).observe(document.getElementById('controlCajasSection')||document.body,{childList:true,subtree:true})}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,1500));else setTimeout(boot,1500);
})();
'''
s += js
P.write_text(s,encoding='utf-8')
print('Catálogos generales movidos al menú superior de Configuración')
